### ISSUE TITLE
Position update bring attitude errors

### ISSUE THREAD

**Issue by improve100** [nordmoen/eskf-rs#3]
Hello, when I update XYZ, the attitude error is also brought in.I don't know why?
![image](https://user-images.githubusercontent.com/6092914/165512664-1716cb41-46f3-468f-93cf-d3e09edfe3b0.png)

**Comment by nordmoen** [comment]
It depends a bit on how you are updating the filter. If your uncertainty during the position update is small then it could affect the orientation. Otherwise it depends on the observations that you feed to the filer.

**Comment by improve100** [comment]
thank you for your response.
