### ISSUE TITLE
Support for integrating angular velocity

### ISSUE THREAD

**Issue by manglemix** [nordmoen/eskf-rs#6]
Are there any plans for adding an alternative predict method that accepts angular velocity instead of just orientation?

**Comment by nordmoen** [comment]
I'm not sure I understand your question. The `predict` method takes acceleration and angular velocity as outputted by an IMU. The job of the filter is to estimate orientation from IMU data and other observations.

**Comment by manglemix** [comment]
The documentation of the `predict` method is `Update the filter, predicting the new state, based on measured acceleration and rotation from an IMU`. So does the filter take rotation or angular velocity?

**Comment by nordmoen** [comment]
Ah, I see where the misunderstanding came in. Yes the `predict` method takes the angular velocity from an IMU. The documentation is not precise enough.

**Comment by manglemix** [comment]
Ah good to know!
